# Generated by Django 2.2 on 2019-05-17 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('upvote', models.IntegerField()),
                ('date_de_commentaire', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication_archivee',
            fields=[
                ('idpa', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Statistiques',
            fields=[
                ('ids', models.IntegerField(primary_key=True, serialize=False)),
                ('nmbr_publication', models.IntegerField()),
                ('nmbr_commentaires', models.IntegerField()),
                ('upvote', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication_enrigistre',
            fields=[
                ('idpe', models.IntegerField(primary_key=True, serialize=False)),
                ('idu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_publication', models.DateField(auto_now_add=True)),
                ('date_de_modification', models.DateField(auto_now=True)),
                ('section', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('upvote', models.IntegerField(default=0)),
                ('titre', models.CharField(max_length=30)),
                ('lauteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-upvote',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('etudiant', 'Etudiant'), ('enseignant', 'Enseignant'), ('moderateur', 'Moderateur')], default='etudiant', max_length=10)),
                ('date_naissance', models.DateField()),
                ('numero_telephone', models.IntegerField()),
                ('promotion', models.CharField(choices=[('1cpi', '1CPI'), ('2cpi', '2CPI'), ('1cs', '1CS'), ('2cs', '2CS'), ('3cs', '3CS')], default='1cpi', max_length=3)),
                ('bio', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fichier_attachee',
            fields=[
                ('idfa', models.IntegerField(primary_key=True, serialize=False)),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Commentaire')),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='commentaire',
            name='commentaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Main.Publication'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='commented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='tag_utilisateur',
            field=models.ManyToManyField(related_name='tag_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
