# Generated by Django 2.2.1 on 2019-05-12 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('ida', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('idc', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('section', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('titre', models.CharField(max_length=30)),
                ('ida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Administration')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('idu', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('idpr', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('promotion', models.CharField(max_length=30)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication_archivee',
            fields=[
                ('idpa', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Statistiques',
            fields=[
                ('ids', models.IntegerField(primary_key=True, serialize=False)),
                ('nmbr_publication', models.IntegerField()),
                ('nmbr_commentaires', models.IntegerField()),
                ('upvote', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('idu', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Publication_enrigistre',
            fields=[
                ('idpe', models.IntegerField(primary_key=True, serialize=False)),
                ('idu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('idp', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('section', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('titre', models.CharField(max_length=30)),
                ('ida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Administration')),
                ('idu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Moderateur',
            fields=[
                ('idm', models.IntegerField(primary_key=True, serialize=False)),
                ('ida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Administration')),
            ],
        ),
        migrations.CreateModel(
            name='Fichier_attachee',
            fields=[
                ('idfa', models.IntegerField(primary_key=True, serialize=False)),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Commentaire')),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='commentaire',
            name='idp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Publication'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='idu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Utilisateur'),
        ),
    ]
