# Generated by Django 2.2.1 on 2019-08-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Name',
            field=models.CharField(default='sasa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Surname',
            field=models.CharField(default='sasa', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
