# Generated by Django 2.2.5 on 2019-09-15 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='lauteur',
            new_name='auteur',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='tag_utilisateur',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='upvote',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='upvote',
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', related_query_name='publication', to='Main.Publication'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', null=True, upload_to='profile_pics'),
        ),
    ]
