# Generated by Django 2.2.4 on 2019-08-05 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_naissance',
        ),
    ]
