# Generated by Django 2.2.4 on 2019-09-17 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20190915_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='duree',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='mod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mod-ban+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='subject',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
