# Generated by Django 2.2.1 on 2019-09-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20190914_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_appoved',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='publication_enregistrer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
