# Generated by Django 2.2.1 on 2019-09-16 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20190915_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication_archivee',
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_enrigstrée',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', related_query_name='auteur', to=settings.AUTH_USER_MODEL),
        ),
    ]
