# Generated by Django 2.2.1 on 2019-09-16 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20190916_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='pub_enrigstrée',
        ),
        migrations.AddField(
            model_name='publication',
            name='users',
            field=models.ManyToManyField(related_name='pubs_eng', related_query_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
