# Generated by Django 2.2.4 on 2019-09-14 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20190816_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='promotion',
            field=models.CharField(choices=[('1cpi', '1CPI'), ('2cpi', '2CPI'), ('1cs', '1CS'), ('2cs', '2CS'), ('3cs', '3CS')], default='1cpi', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='publication_enregistrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Publication'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Etudiant'), ('enseignant', 'Enseignant'), ('moderateur', 'Moderateur'), ('admin', 'A dmin')], default='etudiant', max_length=10),
        ),
    ]
