# Generated by Django 2.2.5 on 2019-09-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20190916_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(choices=[('offtalk', 'OffTalk'), ('professors', 'Professors'), ('clubs', 'Clubs'), ('bachelors', 'Bachelors'), ('1cpi', '1CPI'), ('2cpi', '2CPI'), ('1cs', '1CS'), ('2cs', '2CS'), ('3cs', '3CS')], default=1, max_length=30),
        ),
    ]
