# Generated by Django 2.2.1 on 2019-09-16 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20190916_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='users',
            field=models.ManyToManyField(default=None, related_name='pubs_eng', related_query_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
