# Generated by Django 2.2.5 on 2019-09-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20190914_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='lauteur',
            new_name='auteur',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='upvote',
        ),
    ]
