# Generated by Django 2.2.5 on 2019-09-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20190914_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='tag_utilisateur',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='upvote',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', null=True, upload_to='profile_pics'),
        ),
    ]
