# Generated by Django 2.2.5 on 2019-09-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20190916_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='posts', to='Main.Tags'),
        ),
    ]
