# Generated by Django 2.2.1 on 2019-09-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20190917_0020'),
        ('Main', '0005_auto_20190916_2335'),
    ]

    operations = [
    ]
