# Generated by Django 2.2.5 on 2019-09-18 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name='user_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
