# Generated by Django 2.2.4 on 2019-09-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20190918_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Etudiant'), ('enseignant', 'Enseignant'), ('moderateur', 'Moderateur'), ('admin', 'Admin'), ('clubs', 'Clubs')], default='etudiant', max_length=10),
        ),
    ]
